# Generated by Django 4.1.2 on 2022-10-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_alter_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='fecha_nacimiento',
            new_name='fecha',
        ),
    ]
